version: "3"
services:
  mysql:
    container_name: mysql-codestape
    image: getjv/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
  backend:
    container_name: php-codestape
    image: getjv/php-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - ALLOW_OVERRIDE_OPTION=All
      - APPLICATION_ENV_OPTION=development
      - DOCUMENT_ROOT_CONTEXT=public
    links:
      - mysql
